export const FETCH_EMPLOYEES='FETCH_EMPLOYEES';
export const FETCH_EMPLOYEE_DETAIL = 'FETCH_EMPLOYEE_DETAIL';
export const BEGIN_AJAX_CALL= 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const HANDLE_ERROR ='HANDLE_ERROR';
export const FETCH_SUCCESS = 'FETCH_SUCCESS'